(define (problem asi-problem)
  (:domain asi-domain)
  (:objects first-tower-launchpad s1-antenna-1 s1-antenna-2 s1-antenna-3 s1-antenna-4 s1-antenna-5 s1-antenna-6 - component front above below left right front-below launch-pad - perspective drone1 drone2 - drone)
  (:init
    (= (spent-energy) 0)
    (is-perspective launch-pad first-tower-launchpad)
    (= (required-charge first-tower-launchpad first-tower-launchpad) 0)
    (= (required-charge first-tower-launchpad s1-antenna-1) 29)
    (= (required-charge first-tower-launchpad s1-antenna-2) 29)
    (= (required-charge first-tower-launchpad s1-antenna-3) 30)
    (= (required-charge first-tower-launchpad s1-antenna-4) 30)
    (= (required-charge first-tower-launchpad s1-antenna-5) 29)
    (= (required-charge first-tower-launchpad s1-antenna-6) 29)
    (is-perspective front s1-antenna-1)
    (is-perspective above s1-antenna-1)
    (is-perspective below s1-antenna-1)
    (is-perspective left s1-antenna-1)
    (is-perspective right s1-antenna-1)
    (is-perspective front-below s1-antenna-1)
    (= (required-charge s1-antenna-1 first-tower-launchpad) 29)
    (= (required-charge s1-antenna-1 s1-antenna-1) 0)
    (= (required-charge s1-antenna-1 s1-antenna-2) 1)
    (= (required-charge s1-antenna-1 s1-antenna-3) 2)
    (= (required-charge s1-antenna-1 s1-antenna-4) 2)
    (= (required-charge s1-antenna-1 s1-antenna-5) 2)
    (= (required-charge s1-antenna-1 s1-antenna-6) 2)
    (is-perspective front s1-antenna-2)
    (is-perspective above s1-antenna-2)
    (is-perspective below s1-antenna-2)
    (is-perspective left s1-antenna-2)
    (is-perspective right s1-antenna-2)
    (is-perspective front-below s1-antenna-2)
    (= (required-charge s1-antenna-2 first-tower-launchpad) 29)
    (= (required-charge s1-antenna-2 s1-antenna-1) 1)
    (= (required-charge s1-antenna-2 s1-antenna-2) 0)
    (= (required-charge s1-antenna-2 s1-antenna-3) 2)
    (= (required-charge s1-antenna-2 s1-antenna-4) 2)
    (= (required-charge s1-antenna-2 s1-antenna-5) 2)
    (= (required-charge s1-antenna-2 s1-antenna-6) 2)
    (is-perspective front s1-antenna-3)
    (is-perspective above s1-antenna-3)
    (is-perspective below s1-antenna-3)
    (is-perspective left s1-antenna-3)
    (is-perspective right s1-antenna-3)
    (is-perspective front-below s1-antenna-3)
    (= (required-charge s1-antenna-3 first-tower-launchpad) 30)
    (= (required-charge s1-antenna-3 s1-antenna-1) 2)
    (= (required-charge s1-antenna-3 s1-antenna-2) 2)
    (= (required-charge s1-antenna-3 s1-antenna-3) 0)
    (= (required-charge s1-antenna-3 s1-antenna-4) 1)
    (= (required-charge s1-antenna-3 s1-antenna-5) 2)
    (= (required-charge s1-antenna-3 s1-antenna-6) 2)
    (is-perspective front s1-antenna-4)
    (is-perspective above s1-antenna-4)
    (is-perspective below s1-antenna-4)
    (is-perspective left s1-antenna-4)
    (is-perspective right s1-antenna-4)
    (is-perspective front-below s1-antenna-4)
    (= (required-charge s1-antenna-4 first-tower-launchpad) 30)
    (= (required-charge s1-antenna-4 s1-antenna-1) 2)
    (= (required-charge s1-antenna-4 s1-antenna-2) 2)
    (= (required-charge s1-antenna-4 s1-antenna-3) 1)
    (= (required-charge s1-antenna-4 s1-antenna-4) 0)
    (= (required-charge s1-antenna-4 s1-antenna-5) 2)
    (= (required-charge s1-antenna-4 s1-antenna-6) 2)
    (is-perspective front s1-antenna-5)
    (is-perspective above s1-antenna-5)
    (is-perspective below s1-antenna-5)
    (is-perspective left s1-antenna-5)
    (is-perspective right s1-antenna-5)
    (is-perspective front-below s1-antenna-5)
    (= (required-charge s1-antenna-5 first-tower-launchpad) 29)
    (= (required-charge s1-antenna-5 s1-antenna-1) 2)
    (= (required-charge s1-antenna-5 s1-antenna-2) 2)
    (= (required-charge s1-antenna-5 s1-antenna-3) 2)
    (= (required-charge s1-antenna-5 s1-antenna-4) 2)
    (= (required-charge s1-antenna-5 s1-antenna-5) 0)
    (= (required-charge s1-antenna-5 s1-antenna-6) 1)
    (is-perspective front s1-antenna-6)
    (is-perspective above s1-antenna-6)
    (is-perspective below s1-antenna-6)
    (is-perspective left s1-antenna-6)
    (is-perspective right s1-antenna-6)
    (is-perspective front-below s1-antenna-6)
    (= (required-charge s1-antenna-6 first-tower-launchpad) 29)
    (= (required-charge s1-antenna-6 s1-antenna-1) 2)
    (= (required-charge s1-antenna-6 s1-antenna-2) 2)
    (= (required-charge s1-antenna-6 s1-antenna-3) 2)
    (= (required-charge s1-antenna-6 s1-antenna-4) 2)
    (= (required-charge s1-antenna-6 s1-antenna-5) 1)
    (= (required-charge s1-antenna-6 s1-antenna-6) 0)
    (is-available image front)
    (is-available thermal-image front)
    (is-available image above)
    (is-available thermal-image above)
    (is-available image below)
    (is-available thermal-image below)
    (is-available image left)
    (is-available thermal-image left)
    (is-available image right)
    (is-available thermal-image right)
    (is-available image front-below)
    (is-available thermal-image front-below)
    (is-launch-pad launch-pad)
    (has-capability drone1 camera)
    (is-at drone1 first-tower-launchpad launch-pad)
    (has-capability drone2 camera)
    (has-capability drone2 thermal-camera)
    (is-at drone2 first-tower-launchpad launch-pad)
  )
  (:goal
    (and
      (is-at drone1 first-tower-launchpad launch-pad)
      (is-at drone2 first-tower-launchpad launch-pad)
      (know image s1-antenna-1 left)
      (know image s1-antenna-2 left)
      (know image s1-antenna-3 left)
      (know image s1-antenna-4 left)
      (know image s1-antenna-5 left)
      (know image s1-antenna-6 left)
      (know thermal-image s1-antenna-1 left)
      (know thermal-image s1-antenna-2 left)
      (know thermal-image s1-antenna-3 left)
      (know thermal-image s1-antenna-4 left)
      (know thermal-image s1-antenna-5 left)
      (know thermal-image s1-antenna-6 left)
    )
  )
  (:metric minimize (spent-energy))
)